export { default as About} from './About/About'
export { default as Contact} from './Contact/Contact.js'
export { default as Home} from './Home/Home'
export { default as Services} from './Services/Services'
export { default as SingleProduct} from './SingleProduct/SingleProduct'
export { default as NewProducts} from './NewProducts/NewProducts'
